### ISSUE TITLE
Error: Supplied URL is not a feed, and we can't find any potential candidate in the page.

### ISSUE THREAD

**Issue by mrusme** [fanzeyi/lares#3]
Even though these feeds are valid RSS feeds I can read them e.g. in Feedly, lares says they're not:

- https://drewdevault.com/feed.xml
- http://www.schneier.com/blog/index.rdf
- https://n-o-d-e.net/rss/rss.xml
- http://www.cnx-software.com/feed/
- http://www.notebookcheck.net/News.152.100.html

Maybe the parser has an issue with specific content?

**Comment by mrusme** [comment]
In addition, feedburner URLs seem to be resulting in a crash:

- http://feeds.feedburner.com/Liliputing
- http://feeds.feedburner.com/HighScalability

```
RUST_BACKTRACE=full ./target/debug/lares feed add -g Technology "http://feeds.feedburner.com/Liliputing"                                                                                                                                                                          surf::middleware::logger::native sending request
    req.id 0
    req.method GET
    req.uri http://feeds.feedburner.com/Liliputing
surf::middleware::logger::native request completed
    req.id 0
    req.status 502
    elapsed 106.293173ms
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnquotedValue(10)', /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/xml/mod.rs:391:27
stack backtrace:
   0:        0x102522fde - backtrace::backtrace::libunwind::trace::he0a1acffd944ce3f
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:        0x102522fde - backtrace::backtrace::trace_unsynchronized::ha35c8b21934b5ff7
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:        0x102522fde - std::sys_common::backtrace::_print_fmt::h5e52d5d250a5076b
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x102522fde - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h24bb64d98a7e25d6
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x102547acc - core::fmt::write::h8fdc9cddb01cd8b2
                               at src/libcore/fmt/mod.rs:1076
   5:        0x10251c5e9 - std::io::Write::write_fmt::hcc3030013983bab6
                               at src/libstd/io/mod.rs:1537
   6:        0x102524ee5 - std::sys_common::backtrace::_print::hb08b3b51b5188d8a
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x102524ee5 - std::sys_common::backtrace::print::h97998656489491bc
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x102524ee5 - std::panicking::default_hook::{{closure}}::h95817712c5ff0736
                               at src/libstd/panicking.rs:198
   9:        0x102524c22 - std::panicking::default_hook::h34e085f4e0b1062d
                               at src/libstd/panicking.rs:217
  10:        0x102525445 - std::panicking::rust_panic_with_hook::haf571858f996ac45
                               at src/libstd/panicking.rs:526
  11:        0x102525012 - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:        0x10255a4ff - core::panicking::panic_fmt::h11676ba6a846d9f4
  13:        0x10255a405 - core::result::unwrap_failed::h8830e249b1d39cd9
  14:        0x101bd16be - core::result::Result<T,E>::unwrap::h42f1443cda763f03
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:1005
  15:        0x101b439b8 - feed_rs::xml::XmlEvent::start::{{closure}}::h445e43efcc3f016b
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/xml/mod.rs:391
  16:        0x101b40a47 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h468a693045a4e56b
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:286
  17:        0x101b526d9 - core::option::Option<T>::map::h2839d9a73ead452f
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:453
  18:        0x101b4ccda - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h81035f8c7e6dda86
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/adapters/mod.rs:852
  19:        0x101b2c2fe - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h285e42cda970322e
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/vec.rs:2093
  20:        0x101b2e207 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h5ad0a31dc5247374
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/vec.rs:1995
  21:        0x101b4a158 - core::iter::traits::iterator::Iterator::collect::h7c9dacf2751821e1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:1671
  22:        0x101b4382d - feed_rs::xml::XmlEvent::start::h755e9f34430083dc
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/xml/mod.rs:389
  23:        0x101b414fd - feed_rs::xml::SourceState<R>::fetch_next::h67dd5e3893db2df1
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/xml/mod.rs:183
  24:        0x101b41a34 - feed_rs::xml::SourceState<R>::next::h1b579c34ec4f0742
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/xml/mod.rs:212
  25:        0x101b4210e - feed_rs::xml::ElementSource<R>::next_element_at_depth::h2e34476dc61365ad
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/xml/mod.rs:103
  26:        0x101b42d4d - feed_rs::xml::ElementSource<R>::root::h74cd754955efc664
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/xml/mod.rs:43
  27:        0x101bcce25 - feed_rs::parser::parse_xml::h882feabf079efb01
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/parser/mod.rs:183
  28:        0x101bccb20 - feed_rs::parser::parse::h62ad6b6581f62411
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/feed-rs-0.4.0/src/parser/mod.rs:124
  29:        0x101b7dec7 - lares::remote::RemoteFeed::try_new::{{closure}}::h0552a7e78a536e6f
                               at /Users/mrus/Projects/GitHub/lares/src/remote.rs:25
  30:        0x101b1fa8c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7820886ca525385c
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  31:        0x101b74e04 - lares::cli::FeedCommand::add::{{closure}}::had2f457b218b984f
                               at /Users/mrus/Projects/GitHub/lares/src/cli.rs:134
  32:        0x101b20730 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hab50477a52e6bae9
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  33:        0x101b76b7d - lares::cli::FeedCommand::run::{{closure}}::h0d87eb570fe510db
                               at /Users/mrus/Projects/GitHub/lares/src/cli.rs:256
  34:        0x101b1e490 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0a1c0132eed7ea0d
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  35:        0x101b7b07e - lares::cli::Options::run::{{closure}}::h9de8c72ce85c0cad
                               at /Users/mrus/Projects/GitHub/lares/src/cli.rs:440
  36:        0x101b20030 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8d33f833a4ea63ed
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  37:        0x101beeea9 - lares::cli::{{closure}}::h629ccd274018c455
                               at /Users/mrus/Projects/GitHub/lares/src/lib.rs:17
  38:        0x101b207d0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haf17591a0de7e566
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  39:        0x101bed6c0 - lares::main::main::{{closure}}::h178c088c7f7e6f5c
                               at src/main.rs:3
  40:        0x101b1f360 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h546d7a51cd2e607a
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  41:        0x101bed470 - lares::main::{{closure}}::h04a0b5e09c879248
                               at src/main.rs:1
  42:        0x101b21330 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he5f31767eb21d37a
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  43:        0x101bdcfa5 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}::h84982679c02a120b
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:198
  44:        0x101b91850 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::h7907dcc440c638aa
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:60
  45:        0x101b87f34 - std::thread::local::LocalKey<T>::try_with::hcf06df89bd41ab0f
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  46:        0x101b86f2c - std::thread::local::LocalKey<T>::with::hde46340ad7971936
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  47:        0x101b91554 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h4d4a5fd4ae977905
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:55
  48:        0x101bdcdf1 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::hc18736d680480657
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:196
  49:        0x101ba3026 - async_executor::LocalExecutor::run::{{closure}}::h86faae43af296b53
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-0.1.2/src/lib.rs:339
  50:        0x101ba380a - scoped_tls::ScopedKey<T>::set::h558e90268617d2d1
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  51:        0x101ba2f89 - async_executor::LocalExecutor::run::h5cfaf2c8cd3ce0ab
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-0.1.2/src/lib.rs:337
  52:        0x101ba4710 - async_std::task::executor::run::{{closure}}::{{closure}}::{{closure}}::h2f769e483b8a6bdc
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  53:        0x101ba3930 - scoped_tls::ScopedKey<T>::set::hec8e43af8ac4321e
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  54:        0x101ba322a - async_executor::Executor::enter::hb98cfe6670bf1072
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-0.1.2/src/lib.rs:151
  55:        0x101ba4609 - async_std::task::executor::run::{{closure}}::{{closure}}::h24bf83af33b1fd53
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  56:        0x101ba47d3 - async_std::task::executor::enter::h6e14c61aaf01e75e
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:44
  57:        0x101ba456f - async_std::task::executor::run::{{closure}}::hd1e5785e0fe8c330
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  58:        0x101b87b05 - std::thread::local::LocalKey<T>::try_with::hac93d2eb664c4397
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  59:        0x101b86c27 - std::thread::local::LocalKey<T>::with::h3b69385cef42efed
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  60:        0x101ba44f8 - async_std::task::executor::run::h39509af2dff9665c
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  61:        0x101bdef2a - async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}::h2c28c52c76caaf1a
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:170
  62:        0x101b91aa2 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::he3fa50693892c1d5
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:60
  63:        0x101b873e5 - std::thread::local::LocalKey<T>::try_with::h39f45b8f697e0796
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  64:        0x101b86cd7 - std::thread::local::LocalKey<T>::with::h44be13d1ee35f41e
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  65:        0x101b915d6 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h67df2d3ea31635b2
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:55
  66:        0x101bdee0f - async_std::task::builder::Builder::blocking::{{closure}}::hcd0966bdc9cccf38
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:167
  67:        0x101b87ca5 - std::thread::local::LocalKey<T>::try_with::hc1fed117ceea749f
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  68:        0x101b86e97 - std::thread::local::LocalKey<T>::with::hcdcd4a42996ec32b
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  69:        0x101bdecbc - async_std::task::builder::Builder::blocking::h58affdc3b26dd890
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:160
  70:        0x101b91d96 - async_std::task::block_on::block_on::hbf5d6b65da925073
                               at /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/block_on.rs:33
  71:        0x101b89464 - lares::main::h8418c8f106c12f78
                               at src/main.rs:1
  72:        0x101bdfa8e - std::rt::lang_start::{{closure}}::h6b047f650cfd76ba
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  73:        0x10252570f - std::rt::lang_start_internal::{{closure}}::h61757db93e0a7614
                               at src/libstd/rt.rs:52
  74:        0x10252570f - std::panicking::try::do_call::h908b994d27b7ba54
                               at src/libstd/panicking.rs:348
  75:        0x10252570f - std::panicking::try::heb108336153d9e3c
                               at src/libstd/panicking.rs:325
  76:        0x10252570f - std::panic::catch_unwind::h5937a18f6925fee9
                               at src/libstd/panic.rs:394
  77:        0x10252570f - std::rt::lang_start_internal::hcd84a36052901671
                               at src/libstd/rt.rs:51
  78:        0x101bdfa71 - std::rt::lang_start::hf741a451c930fa00
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  79:        0x101b894e2 - main
```

**Comment by mrusme** [comment]
I might have found a clue for the first set of URLs:

```
▲ ./target/debug/lares feed add -g People "https://drewdevault.com/feed.xml"                                                                                                                                                                                     feature/docker_enhancements ⬢
surf::middleware::logger::native sending request
    req.id 0
    req.method GET
    req.uri https://drewdevault.com/feed.xml
surf::middleware::logger::native request completed
    req.id 0
    req.status 302
    elapsed 529.795373ms
Error: Supplied URL is not a feed, and we can't find any potential candidate in the page.
```

The feed returns a 302 which needs to be followed. If I curl that URL, get the url from the 302 and add it explicitly to lares it works:

```
△ ./target/debug/lares feed add -g People "https://drewdevault.com/blog/index.xml"                                                                                                                                                                           feature/docker_enhancements 13m ⬢
surf::middleware::logger::native sending request
    req.id 0
    req.method GET
    req.uri https://drewdevault.com/blog/index.xml
surf::middleware::logger::native request completed
    req.id 0
    req.status 200
    elapsed 654.049764ms
Feed added!
ID: 11
Name: Blogs on Drew DeVault's blog
Feed URL: https://drewdevault.com/blog/index.xml
Site URL: https://drewdevault.com

Feed added to group People
```

It seems like something in there doesn't follow the 302 but instead tries to parse the initial response. Will investigate further.

**Comment by mrusme** [comment]
So, it turns out that the HTTP client library that's being used here (Surf) was not able to do HTTP redirects until only very recently. There is an  [issue](https://github.com/http-rs/surf/issues/18) and a [PR](https://github.com/http-rs/surf/pull/195). The PR was merged and released with the latest [2.0.0-alpha.5](https://github.com/http-rs/surf/releases/tag/v2.0.0-alpha.5) version. I've created a [feature branch](https://github.com/mrusme/lares/tree/feature/redirects) in which I tried to upgrade to that version and adjust the the `try_new` function in `remote.rs` to use the redirect middleware. 

However, I'm running into an issue with what seems like the error handling in `error.rs`. It seems like `surf::Exception` does not exist anymore, so I used `surf::Error` there. Unfortunately this seems to have an impact on tide:

```
error[E0599]: no method named `as_dyn_error` found for reference `&tide::Error` in the current scope
  --> src/error.rs:34:13
   |
34 |     #[error("{}", _0)]
   |             ^^^^ method not found in `&tide::Error`
   |
  ::: /Users/mrus/.cargo/registry/src/github.com-1ecc6299db9ec823/http-types-2.4.0/src/error.rs:15:1
   |
15 | pub struct Error {
   | ----------------
   | |
   | doesn't satisfy `tide::Error: std::error::Error`
   | doesn't satisfy `tide::Error: thiserror::private::AsDynError`
   |
   = note: the method `as_dyn_error` exists but the following trait bounds were not satisfied:
           `tide::Error: std::error::Error`
           which is required by `tide::Error: thiserror::private::AsDynError`
           `&tide::Error: std::error::Error`
           which is required by `&tide::Error: thiserror::private::AsDynError`

error: aborting due to previous error
```

I don't quite understand how the `pub enum Error` works, hence I'm having a hard time fixing it. @fanzeyi maybe you happen to have a hint for here? Would be nice to open a PR in order to fix this issue. :-)

**Comment by fanzeyi** [comment]
For the FeedBurner URLs, it looks like surf is not reporting 502 as errors so lares incorrectly trying to parse the error response as the feed. 

This is my first project uses surf but it seems it still has some rough edges. Instead of replacing it with an alpha version I'm more willing to just write some code around it to handle these cases. (502, following redirections etc.). I'll work on these.

**Comment by fanzeyi** [comment]
As of the `Error` issue, it seems from `tide` 2.0 they no longer implement `std::error::Error` for `tide::Error`, but `thiserror` is only able to automatically convert errors that implements `std::error::Error`. I think the resolution is probably manually implement `From<tide::Error> for lares::Error` and call `tide::Error`'s [`as_ref`](https://docs.rs/http-types/2.2.1/src/http_types/error.rs.html#152-156).

**Comment by fanzeyi** [comment]
For the FeedBurner 502 issue, it's caused by surf incorrectly having isahc adding `Transfer-Encoding: chunked` to the request while nothing is actually in the request body. (see https://github.com/http-rs/surf/issues/175).

Manually adding `Content-Length: 0` could work around this issue. Will push soon.

**Comment by fanzeyi** [comment]
Okay, fixed one more bug. I'm releasing v0.2.2 and it should accept all the URLs you posted in this issue.

**Comment by mrusme** [comment]
@fanzeyi awesome work, thank you!
